# Generated by Django 5.0.7 on 2024-08-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0003_unidad_alter_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.categoria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventasApp.unidad')),
            ],
        ),
    ]
